name: buuk_test
description: Buuk Test Application

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.1
  bloc: ^8.1.0
  cached_network_image: ^3.2.1
  flutter_easyloading: ^3.0.5
  json_serializable: ^6.2.0
  http: ^0.13.4
  get_it: ^7.2.0
  pretty_dio_logger: ^1.1.1
  dio: ^4.0.6
  intl: ^0.17.0
  fluttertoast: ^8.0.9
  equatable: ^2.0.3
  flutter_secure_storage: ^5.0.2
  retrofit: ^3.0.1+1
  logger: ^1.1.0
  flutter_svg: ^1.1.1+1
  package_info_plus: ^1.4.2
  introduction_screen: ^3.0.2
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  retrofit_generator: ^4.0.1
  build_runner: ^2.1.7

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
